# Generated by Django 3.1.5 on 2021-02-16 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_bid_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionListing',
            new_name='Listing',
        ),
    ]
