# Generated by Django 3.1.5 on 2021-02-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210216_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='photo',
        ),
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Image URL (optional)'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('BOOK', 'Books'), ('CLOTH', 'Clothing'), ('CHILD', 'Children'), ('ELEC', 'Electronics'), ('FURN', 'Furniture'), ('KIT', 'Kitchen'), ('ART', 'Music/Arts'), ('SER', 'Services'), ('TOOL', 'Tools'), ('OTHER', 'Other')], max_length=5, null=True, verbose_name='Category (optional)'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(verbose_name='Starting Bid'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
