# Generated by Django 3.1.5 on 2021-02-16 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='current_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='status',
        ),
    ]
