# Generated by Django 3.1.5 on 2021-02-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210216_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('a', 'Books'), ('b', 'Clothing'), ('c', 'Children'), ('d', 'Electronics'), ('e', 'Furniture'), ('f', 'Kitchen'), ('g', 'Music/Arts'), ('h', 'Services'), ('i', 'Tools'), ('j', 'Other')], default=('j', 'Other'), max_length=1, null=True, verbose_name='Category (optional)'),
        ),
    ]
