# Generated by Django 3.1.5 on 2021-02-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20210216_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('a', 'All Categories'), ('b', 'Books'), ('c', 'Clothing'), ('d', 'Children'), ('e', 'Electronics'), ('f', 'Furniture'), ('g', 'Kitchen'), ('h', 'Music/Arts'), ('i', 'Services'), ('j', 'Tools'), ('k', 'Other')], default=('a', 'All Categories'), max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.FloatField(),
        ),
    ]
