# Generated by Django 3.1.5 on 2021-02-19 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_listing_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchlist',
        ),
    ]
