# Generated by Django 3.1.5 on 2021-02-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_listing_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='watchers',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
