# Generated by Django 3.1.5 on 2021-02-19 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listing_watchers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='watchers',
        ),
    ]
