# Generated by Django 3.1.5 on 2021-02-19 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_auto_20210219_0120'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Watchlist',
        ),
    ]
