# Generated by Django 3.1.5 on 2021-02-20 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_auto_20210220_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(blank=True, default=models.FloatField(), null=True),
        ),
    ]
