# Generated by Django 3.1.5 on 2021-02-20 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0028_auto_20210220_0352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='bidder',
            new_name='top_bidder',
        ),
    ]
