# Generated by Django 3.1.5 on 2021-02-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_auto_20210220_0622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(blank=True, choices=[('a', 'All Categories'), ('b', 'Books'), ('c', 'Clothing'), ('d', 'Children'), ('e', 'Electronics'), ('f', 'Furniture'), ('g', 'Kitchen'), ('h', 'Music/Arts'), ('i', 'Services'), ('j', 'Tools'), ('k', 'Other')], max_length=1, null=True),
        ),
    ]
