# Generated by Django 3.1.5 on 2021-02-21 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0038_auto_20210221_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Books'), ('b', 'Clothing'), ('c', 'Children'), ('d', 'Electronics'), ('e', 'Furniture'), ('f', 'Kitchen'), ('g', 'Music/Arts'), ('h', 'Services'), ('i', 'Tools'), ('j', 'Vehicles'), ('k', 'Other')], max_length=1, null=True),
        ),
    ]
