# Generated by Django 3.1.5 on 2021-02-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0040_auto_20210221_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Books'), ('b', 'Children'), ('c', 'Clothing'), ('d', 'Decoration'), ('e', 'Electronics'), ('f', 'Furniture'), ('g', 'Kitchen'), ('h', 'Music/Arts'), ('i', 'Office'), ('j', 'Services'), ('k', 'Tools'), ('l', 'Vehicles'), ('m', 'Other')], max_length=1, null=True),
        ),
    ]
