# Generated by Django 3.1.5 on 2021-02-23 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_auto_20210223_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
