# Generated by Django 3.1.5 on 2021-02-23 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0047_auto_20210223_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_time',
        ),
    ]
