# Generated by Django 3.1.5 on 2021-02-24 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0049_listing_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
