# Generated by Django 3.1.5 on 2021-02-24 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0050_auto_20210224_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='date_time',
        ),
    ]
