# Generated by Django 3.1.5 on 2021-03-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0052_auto_20210224_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('a', 'Beauty'), ('b', 'Books'), ('c', 'Children'), ('d', 'Clothing'), ('e', 'Decoration'), ('f', 'Electronics'), ('g', 'Furniture'), ('h', 'Kitchen'), ('i', 'Music/Arts'), ('j', 'Office'), ('k', 'Services'), ('l', 'Tools'), ('m', 'Vehicles'), ('n', 'Other')], max_length=1, null=True),
        ),
    ]
